export interface Advancement {
  id: string;
  name: string;
  hint: string;
  xp: number;
}

export const ADVANCEMENTS: Advancement[] = [
  { id: "getting_wood", name: "Getting Wood", hint: "Punch a log", xp: 10 },
  { id: "benchmarking", name: "Benchmarking", hint: "Craft a crafting table", xp: 15 },
  { id: "time_to_mine", name: "Time to Mine!", hint: "Craft a pickaxe", xp: 15 },
  { id: "getting_an_upgrade", name: "Getting an Upgrade", hint: "Craft a stone pickaxe", xp: 20 },
  { id: "hot_topic", name: "Hot Topic", hint: "Smelt something in a furnace", xp: 20 },
  { id: "acquire_hardware", name: "Acquire Hardware", hint: "Smelt an iron ingot", xp: 25 },
  { id: "diamonds", name: "Diamonds!", hint: "Mine diamond ore", xp: 40 },
  { id: "cover_me_diamond", name: "Cover Me With Diamonds", hint: "Wear a diamond chestplate", xp: 50 },
  { id: "enchanter", name: "Enchanter", hint: "Reach XP level 15", xp: 30 },
  { id: "we_need_to_go_deeper", name: "We Need to Go Deeper", hint: "Enter the Nether", xp: 40 },
  { id: "nether_fortress", name: "A Terrible Fortress", hint: "Walk a nether brick walkway", xp: 35 },
  { id: "into_fire", name: "Into Fire", hint: "Pick up a blaze rod", xp: 30 },
  { id: "local_brewery", name: "Local Brewery", hint: "Brew or hold a potion", xp: 25 },
  { id: "the_end", name: "The End?", hint: "Enter the End dimension", xp: 50 },
  { id: "free_the_end", name: "Free the End", hint: "Defeat the Void Wyrm", xp: 400 },
  { id: "the_end_again", name: "The End.", hint: "Leave the End after the Wyrm", xp: 80 },
  { id: "monster_hunter", name: "Monster Hunter", hint: "Slay a creeper", xp: 15 },
  { id: "sniper_duel", name: "Sniper Duel", hint: "Kill with a bow", xp: 20 },
  { id: "postmortal", name: "Postmortal", hint: "Use a totem", xp: 40 },
  { id: "return_to_sender", name: "Return to Sender", hint: "Deflect a ghast fireball", xp: 35 },
  { id: "uneasy_alliance", name: "Uneasy Alliance", hint: "Rescue a ghast to the overworld", xp: 40 },
  { id: "hidden_in_depths", name: "Hidden in the Depths", hint: "Find ancient debris", xp: 60 },
  { id: "cover_me_netherite", name: "Cover Me in Debris", hint: "Wear netherite armor", xp: 80 },
  { id: "adventuring_time", name: "Adventuring Time", hint: "Visit 12 biomes", xp: 50 },
  { id: "sweet_dreams", name: "Sweet Dreams", hint: "Sleep in a bed", xp: 15 },
  { id: "what_a_deal", name: "What a Deal!", hint: "Trade with a villager", xp: 20 },
  { id: "hired_help", name: "Hired Help", hint: "Summon an iron golem", xp: 25 },
  { id: "zombies", name: "Zombie Doctor", hint: "Cure a zombie villager", xp: 30 },
  { id: "two_birds", name: "Two Birds One Arrow", hint: "Kill two phantoms", xp: 25 },
  { id: "arbalistic", name: "Arbalistic", hint: "Kill five unique mobs", xp: 30 },
  { id: "hero_village", name: "Hero of the Village", hint: "Defend a village", xp: 40 },
  { id: "voluntary_exile", name: "Voluntary Exile", hint: "Kill a raid captain", xp: 25 },
  { id: "how_did_we_get_here", name: "How Did We Get Here?", hint: "Have absorption and regen at once", xp: 40 },
  { id: "a_furious_cocktail", name: "A Furious Cocktail", hint: "Eat a golden apple in a duel", xp: 20 },
  { id: "subspace_bubble", name: "Subspace Bubble", hint: "Use a nether portal", xp: 20 },
  { id: "eye_spy", name: "Eye Spy", hint: "Follow an eye of ender", xp: 30 },
  { id: "the_city", name: "The City at the End of the Game", hint: "Reach outer End islands", xp: 50 },
  { id: "sky_is_limit", name: "Sky's the Limit", hint: "Find elytra", xp: 80 },
  { id: "great_view", name: "Great View From Up Here", hint: "Levitate from a shulker", xp: 30 },
  { id: "dual_first_blood", name: "First Blood", hint: "Get a Dual kill", xp: 25 },
  { id: "bed_wars_win", name: "Bed Destroyer", hint: "Play Bed Wars", xp: 30 },
  { id: "sky_wars_win", name: "Last Standing", hint: "Play Sky Wars", xp: 30 },
  { id: "ctf_cap", name: "Flag Bearer", hint: "Capture a flag", xp: 30 },
  { id: "ol_betsy", name: "Ol' Betsy", hint: "Shoot a crossbow", xp: 15 },
  { id: "fishy_business", name: "Fishy Business", hint: "Catch a fish", xp: 10 },
  { id: "tactical_fishing", name: "Tactical Fishing", hint: "Pick up a fish with a bucket", xp: 10 },
  { id: "serious_dedication", name: "Serious Dedication", hint: "Use a netherite hoe", xp: 20 },
  { id: "wax_on", name: "Wax On", hint: "Wax a copper block", xp: 10 },
  { id: "star_trader", name: "Star Trader", hint: "Reach the world border in spirit", xp: 20 },
  { id: "isnt_it_iron_pick", name: "Isn't It Iron Pick", hint: "Craft an iron pickaxe", xp: 20 },
  { id: "ice_bucket_challenge", name: "Ice Bucket Challenge", hint: "Obtain obsidian", xp: 20 },
  { id: "not_today", name: "Not Today, Thank You", hint: "Block with a shield", xp: 15 },
  { id: "take_aim", name: "Take Aim", hint: "Shoot something with a bow", xp: 10 },
  { id: "suit_up", name: "Suit Up", hint: "Wear any armor", xp: 10 },
  { id: "stone_age", name: "Stone Age", hint: "Mine stone with a pickaxe", xp: 10 },
];

export const ADV_BY_ID = new Map(ADVANCEMENTS.map((a) => [a.id, a]));
